[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.prestart]
cmds = ["ffmpeg -version"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
