[phases.setup]
nixPkgs = ["python311", "which"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "nix-env -iA nixpkgs.ffmpeg-full"
]

[phases.prestart]
cmds = ["ffmpeg -version"]

[start]
cmd = "export PATH=$PATH:/nix/var/nix/profiles/default/bin && uvicorn main:app --host 0.0.0.0 --port $PORT"
